### PR TITLE
frr: update to 9.0.1

### PR DESCRIPTION
**Pull request by KanjiMonster**
Import fhe recipes from upstream [1] and update the bbappend accordingly. Since FRR 9.0 needs a newer libyang, import the libyang recipe from OE master was well, and drop our own recipe.

[1] https://github.com/openembedded/meta-openembedded/tree/6f1d32a9bfb550b32ffe5746e7f57732fbf9a371/meta-networking/recipes-protocols/frr

### CODE REVIEW

**Comment by jklare** [comment]
There are quite a couple of changes / files added which are not directly (explicitly) mentioned in the commit messages. I think this can be improved by either adding some more explanations about those specific files and their purpose in the commit message or by linking to other relevant release notes / change logs which explain why those are needed.

**Comment by KanjiMonster** [comment]
Updated the FRR commit to also include a link to the repo, as the patch was accepted upstream, and described a bit more what was changed in the bbappend.

**Comment by KanjiMonster** [comment]
Looks like at least OSPF sometimes temporarily installs a duplicate route to an existing on-link route with a different metric, confusing baseboxd.

Will need to add a workaround to handle that there.

**Comment by KanjiMonster** [comment]
Fix/workaround in https://github.com/bisdn/meta-switch/pull/165

**Review by rubensfig — APPROVED** [review]

**Pull request merged**
