### PR TITLE
update to frr version 8.2

### PR DESCRIPTION
**Pull request by jklare**
* drop patch that is now included upstream

Signed-off-by: Jan Klare <jan.klare@bisdn.de>

### CODE REVIEW

**Review by KanjiMonster — APPROVED** [review]

**Comment by KanjiMonster** [comment]
Can you update the link in the commit to https://github.com/FRRouting/frr/releases/tag/frr-8.2.2 ?

**Comment by jklare** [comment]
I can, but the commit with the tag 8.2.2 does not include any useful information regarding the changes as far as I know (which is why I sticked with this one).

**Comment by KanjiMonster** [comment]
That's why I linked the release and not just the tag.

**Comment by jklare** [comment]
done

**Comment by hilmarm** [comment]
lgtm, all comments have been addressed

**Review by hilmarm — COMMENTED** [review]
lgtm

**Pull request merged**
